### ISSUE TITLE
Could you provide inference code

### ISSUE THREAD

**Issue by qilong-zhang** [jdfxzzy/DPMN#1]
Hi, my request is to perform super-resolution restoration on a image, could you provide the relevant code? Thanks~

**Comment by jdfxzzy** [comment]
Hello, I think it is very easy for you to implement the code by yourself. First, you can use the ``PIL`` package in Python to load the image you want to perfrom super-resolution. Then, you can use ``torchvision.transforms`` to convert this image to ``tensor``. After these steps, you can use our model to do super-resolution with similar workflow as our code.

**Comment by qilong-zhang** [comment]
> Hello, I think it is very easy for you to implement the code by yourself. First, you can use the `PIL` package in Python to load the image you want to perfrom super-resolution. Then, you can use `torchvision.transforms` to convert this image to `tensor`. After these steps, you can use our model to do super-resolution with similar workflow as our code.

Thank you for your reply. I am not very familiar with this field and then I see that your model seems to rely on other models as well. I have tried to make modifications to the `TATT`, but I didn't get it to work. So I would like to have an inference code to use directly.

my code is
```python
image_lr = transforms.ToTensor()(Image.open('./val_data/20230317.jpeg').convert('RGB')).unsqueeze(0).cuda()
print(image_lr.shape)
images_sr = model(image_lr) 
```
I use `crnn.pth`, but the above code will report errors
```
conv_feature = torch.cat([conv_feature, position2d],1) # batch, 128(64+64), 32, 128
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 240000 but got size 1024 for tensor number 1 in the list.
```

**Comment by jdfxzzy** [comment]
Considering that you are not familar with this field, I want to inform you about two key points to help you decide whether our model is suitable for your requirement:
(1) Indeed, our model relies on other models because according to our paper, we aims to improve the performance of existing STISR models. Please notice that our model is used to do "scene text image super-resolution", rather than "single image super-resolution". The difference between the two tasks are thoroughly illustrated in our paper. So, if your image is not what we used in our task, our model may fail to meet your requirement. I suggest you to read our paper, and compare your target image with images in Figure 5 in our paper. If your images are not this kind, then I am sorry to inform that our model may not suitable for you.
(2) If you are sure you image can be processed with our model, please cut it with the region of text, like in Figure 5 in our paper. Then, you need to resize it to $16\times 64$ because our model only accept the input of this size. This is the common practice of this field and all the existing models are similar. You can also refer to the paper and code of TSRN and TATT for more reference.

**Comment by qilong-zhang** [comment]
Thanks for your reply! I know why I fail

**Comment by 0-Maxwei-0** [comment]
> Thanks for your reply! I know why I fail

hi, have you solved this problem?
