### ISSUE TITLE
Question about text mask

### ISSUE THREAD

**Issue by chhkang** [jdfxzzy/DPMN#2]
Hi, thanks for your contribution. I am very inspired by your work.

I run the code with released pretrained model, and the output of text prior module (VisionLAN) seems like one dimensional vector, shape of torch.Size([6, 37]) tensor([6.]) on the inference sequence.

Can you tell me the way to generate or visualize the mask of PGRM module output which is  represent ${P_G^i}$ and ${P_S^i}$ on Figure 3? 

Thanks,
Best regards.

**Comment by jdfxzzy** [comment]
Thank you for your appreciation and valuable feedback! Indeed, the size of ``label_lr`` and ``label_length`` is what you mentioned, and I must point out that this is not $P_G^i$. As you can see in my code, we use the function ``test_acc_counter.convert(label_lr, label_length)`` to generate the recognition result of VisionLAN and then use the function ``make_standard_text`` to create $P_G^i$. If there is nothing wrong with your runtime environment, I think you can successfully get $P_G^i$. If you are interested in how to convert the tensor to characters, I think you need to refer to the paper and code of VisionLAN of help because we directly call the function provided by its author. If you are interested in how to render $P_G^i$, you need to read the code of ``make_standard_text`` and its origin paper (https://arxiv.org/abs/1908.03047).

According to your feedback, I checked my released model and I find that I forgot to add the ``--mask`` parameter in ``run_testing.sh``. Without this parameter, you may fail to load the model and unable to get $P_S^i$. I feel very sorry for my mistake and I will update these scripts. You can add this parameter to the script and have another try.

**Comment by chhkang** [comment]
Ah, below codes makes the artificial mask. I misunderstood that the VisionLAN directly make mask. Thanks for detail explanation.

**Comment by jdfxzzy** [comment]
You are welcome. Thank you again for your appreciation of our work.
