### ISSUE TITLE
Is this useful for Chinese text image?

### ISSUE THREAD

**Issue by 1126138640** [jdfxzzy/DPMN#3]
Is this useful for Chinese text image?

**Comment by jdfxzzy** [comment]
I am sorry to inform you that because all the PSNs mentioned in our paper are pre-trained on TextZoom, which is an English dataset, we also only test the ability of our model on this dataset. So, I am not sure whether our model works well on Chinese text images. However, if you have a PSN pre-trained on a Chinese dataset, I think you can try to train our model by yourself following our paper. Parhaps it can also works well on that dataset.

**Comment by 1126138640** [comment]
Thank you for your reply. I'll explore it again.
