### ISSUE TITLE
Does this work for paragraph based text?

### ISSUE THREAD

**Issue by kenhuang1964** [jdfxzzy/DPMN#5]
Awesome work! I'm wondering if it works for paragraph-based text?

**Comment by jdfxzzy** [comment]
Thank you for your appreciation to our work. For your question, I am afraid that our work is not suitable for paragraph-based text because our work is based on the TextZoom dataset and several current STISR methods, such as TSRN and TATT. To the best of my knowledge, there is no such images in the TextZoom dataset. So I think this work is not suitable for paragraph-based text. However, I still encourage that you could have a try.

**Comment by kenhuang1964** [comment]
Thanks!
