### ISSUE TITLE
Pre-trained weight

### ISSUE THREAD

**Issue by vietpho** [jdfxzzy/DPMN#6]
I've encountered some difficulties with accessing the pre-trained weights through the Baidu links provided. Due to my location or other technical issues, I have been unable to download the necessary files.
So I kindly request an alternative method to access the weights. If it's not too much trouble, could you please send the pre-trained weights directly to my email at [vietnamjohnmat@gmail.com]? A Google Drive link would also be an excellent solution.

I truly appreciate the effort and innovation behind your work, and I am grateful for your consideration of my request.

Thank you very much for your time and support.

**Comment by jdfxzzy** [comment]
Thank you for your appreciation to our work! I am sorry that I have not see this issue until today because I am very busy these days. We have uploaded our pre-trained weights to the Google Drive, and links are as follows:
DPMN with TATT-ASTER as PSN: https://drive.google.com/file/d/1keM__l4aj26b24pq85UPkUKhZjS6hdXq/view?usp=sharing
DPMN with TATT-CRNN as PSN: https://drive.google.com/file/d/1226-SZ6YAsZh_a5-5GmGEvQn51ntDskj/view?usp=sharing
DPMN with TATT-MORAN as PSN: https://drive.google.com/file/d/1K23n0xuzLhbsKxOLzBmzA9tDXWs2q5it/view?usp=sharing
