### ISSUE TITLE
questions about Tables

### ISSUE THREAD

**Issue by Video54367** [jdfxzzy/DPMN#7]
Hello, thanks for your work. I thoroughly enjoyed reading the paper and I feel confused about some table in your paper,they dazzled me.
In the Table 1,I tried to add the accuracies of the three splits of the TextZoom and divide the by 3 altogether to get the average accuracy, but the result wasn't exactly consistent with yours ,so I wonder your way.
In the Table 2, the average recognition accuracy is very different with that in the Table 1,Why and How are they calculated?
I'm just a beginner,forgive my ignorance,again,thank you so mch!

**Comment by jdfxzzy** [comment]
Thank you for your appreciation to our work! For your **first** question, actually, following previous works, such as TSRN, TBSRN and TATT, we adopt the weighted average instead of the arithmetic mean value. Take TSRN+DPMN as an example, that is (74.43 * 1619 + 56.41 * 1411 + 39.24 * 1343) / (1619 + 1411 + 1343) = 57.81. For your **second** question, the average recognition accuracy in Table 2 is actually the average value among the three recognizers. Take TSRN+DPMN as an example, that is (57.81 + 43.68 + 52.80) / 3 = 51.43.
